set_property PACKAGE_PIN E21 [get_ports {V_5V5P_SYNC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {V_5V5P_SYNC[0]}]
set_property PACKAGE_PIN D22 [get_ports {V_15VN_SYNC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {V_15VN_SYNC[0]}]
set_property PACKAGE_PIN E22 [get_ports {V_15VP_SYNC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {V_15VP_SYNC[0]}]
set_property PACKAGE_PIN D20 [get_ports {V_30VN_SYNC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {V_30VN_SYNC[0]}]
set_property PACKAGE_PIN C20 [get_ports {V_100VP_SYNC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {V_100VP_SYNC[0]}]

set_property PACKAGE_PIN U20 [get_ports CPU_RESET]
set_property IOSTANDARD LVCMOS33 [get_ports CPU_RESET]

set_property PACKAGE_PIN Y18 [get_ports USER_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports USER_CLK]

set_property PACKAGE_PIN R19 [get_ports USB_UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports USB_UART_RX]
set_property PACKAGE_PIN P19 [get_ports USB_UART_TX]
set_property IOSTANDARD LVCMOS33 [get_ports USB_UART_TX]

# Properties for Bitstream generation for external Flash usage.
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN DISABLE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 40 [current_design]